version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "inhooks"
    binary: "inhooks"
    main: ./cmd/api/main.go
    goos:
      - linux
      - darwin
      - windows
    env:
      - CGO_ENABLED=0

archives:
  - format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

dockers:
  - image_templates:
      - "ghcr.io/didil/inhooks:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/didil/inhooks:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/didil/inhooks:{{ .Tag }}"
    image_templates:
      - "ghcr.io/didil/inhooks:{{ .Tag }}-amd64"
      - "ghcr.io/didil/inhooks:{{ .Tag }}-arm64"
