version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "inhooks"
    binary: "inhooks"
    main: ./cmd/api/main.go
    goos:
      - linux
      - darwin
      - windows
    env:
      - CGO_ENABLED=0

archives:
  - format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

kos:
  - repository: ghcr.io/kusold/inhooks
    tags:
      - "{{.Version}}"
      - latest
    # Bare uses a tag on the $KO_DOCKER_REPO without anything additional.
    bare: true
    # Whether to preserve the full import path after the repository name.
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

    # Base image to publish to use.
    base_image: alpine
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
