// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/services/queue_metrics_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/didil/inhooks/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockQueueMetricsService is a mock of QueueMetricsService interface.
type MockQueueMetricsService struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMetricsServiceMockRecorder
}

// MockQueueMetricsServiceMockRecorder is the mock recorder for MockQueueMetricsService.
type MockQueueMetricsServiceMockRecorder struct {
	mock *MockQueueMetricsService
}

// NewMockQueueMetricsService creates a new mock instance.
func NewMockQueueMetricsService(ctrl *gomock.Controller) *MockQueueMetricsService {
	mock := &MockQueueMetricsService{ctrl: ctrl}
	mock.recorder = &MockQueueMetricsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueMetricsService) EXPECT() *MockQueueMetricsServiceMockRecorder {
	return m.recorder
}

// UpdateMetrics mocks base method.
func (m *MockQueueMetricsService) UpdateMetrics(ctx context.Context, f *models.Flow, sink *models.Sink) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetrics", ctx, f, sink)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetrics indicates an expected call of UpdateMetrics.
func (mr *MockQueueMetricsServiceMockRecorder) UpdateMetrics(ctx, f, sink interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetrics", reflect.TypeOf((*MockQueueMetricsService)(nil).UpdateMetrics), ctx, f, sink)
}
