name: CI

permissions:
  contents: write
  pull-requests: write

on: [push, pull_request]
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"

      - name: Start Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: 6.2.6

      - name: Install tools
        run: make install-tools

      - name: Build
        run: GOFLAGS=-v make build

      - name: Lint
        run: make lint

      - name: Test
        env:
          APP_ENV: test
          REDIS_INHOOKS_DB_NAME: test
          HOST: localhost
          PORT: 3001
          REDIS_URL: "redis://localhost:6379"
        run: GOFLAGS=-v make test

  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          command: manifest
          release-type: go

  release:
    runs-on: ubuntu-latest
    needs: [build, release-please]
    if: needs.release-please.outputs.release_created
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
