name: CI

on: [push, pull_request]
jobs:
  build_app:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.x"

      - name: Start Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: 6.2.6

      - name: Install tools
        run: make install-tools

      - name: Build
        run: GOFLAGS=-v make build

      - name: Lint
        run: make lint

      - name: Test
        env:
          APP_ENV: test
          REDIS_INHOOKS_DB_NAME: test
          HOST: localhost
          PORT: 3001
          REDIS_URL: "redis://localhost:6379"

        run: GOFLAGS=-v make test
